apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vprodb-ssm-secrets
  namespace: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ssm-backend
    kind: ClusterSecretStore
  target:
    name: app-secret
  data:
    - secretKey: db-root-pass
      remoteRef:
        key: /prod/vprodb/root-pass
    - secretKey: db-user-pass
      remoteRef:
        key: /prod/vprodb/user-pass